{{- if .Values.configMaps.gameContent.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conference-games.fullname" . }}-content
  labels:
    {{- include "conference-games.labels" . | nindent 4 }}
    app.kubernetes.io/component: content
  {{- with .Values.configMaps.gameContent.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  sentences.json: |
    {{- .Files.Get "content/sentences.json" | nindent 4 }}
  acronyms.json: |
    {{- .Files.Get "content/acronyms.json" | nindent 4 }}
{{- end }}