apiVersion: v1
kind: Service
metadata:
  name: {{ include "conference-games.fullname" . }}-frontend
  labels:
    {{- include "conference-games.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "conference-games.frontend.selectorLabels" . | nindent 4 }}